"""`divineos prs` — surface local branches without remote PRs.

Andrew 2026-06-09: tonight had 4 branches pushed but no PR opened
because I forgot to run ``gh pr create`` after each push. The gap was
invisible until Andrew pointed at the open-PR count and asked why my
recent branches weren't showing.

This command compares local branches against ``gh pr list`` and names
the branches that need a PR. Read-only by default; ``--open-missing``
runs ``gh pr create --fill`` (or ``--body`` from ``divineos audit
prepare-merge`` for guardrail-touching branches) for each gap.

Guardrail-aware opening (Andrew 2026-06-18): the prior ``--open-missing``
used ``gh pr create --fill`` unconditionally, which copies the branch's
commit message into the PR body. For branches that don't touch any
guardrail file, that's fine — the PR opens, CI runs, life is good.
For branches that DO touch a guardrail file, the commit message
typically lacks the ``External-Review`` trailer (commits are not
blocked over missing trailers per Aletheia's Finding 78 — commits are
work-preservation; the real boundary is push-to-main and squash-merge).
So ``--fill`` opens a PR whose body lacks the trailer, the
multi-party-review CI check correctly fails, and the operator burns a
cycle filing confirms after the failure.

The structural fix: detect guardrail-touching branches at open time
and refuse to use ``--fill`` for them. The right body is generated by
``divineos audit prepare-merge <round-id>``. If no round exists or
confirms are missing, refuse the open and name the workflow (file
round, file CONFIRMs, then re-run). If a round IS ready, the PR opens
with the right body the first time.

Same shape Andrew named via GATE-GATE: when the same workflow gap
keeps biting, the right answer is the OS connecting the existing
pieces, not the operator remembering the dance.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import click


def _run(args: list[str], timeout: float = 10.0) -> tuple[int, str, str]:
    """Run a command, return (rc, stdout, stderr). No raise on failure."""
    try:
        proc = subprocess.run(args, capture_output=True, text=True, timeout=timeout, check=False)
        return proc.returncode, proc.stdout, proc.stderr
    except (OSError, subprocess.TimeoutExpired) as e:
        return 1, "", str(e)


def _local_branches_with_remote() -> list[str]:
    """Return local branches that have a corresponding origin/<branch>
    on the remote. A branch with no remote can't have a PR open against
    it from this side, so we filter early."""
    rc, out, _ = _run(["git", "for-each-ref", "--format=%(refname:short)", "refs/heads/"])
    if rc != 0:
        return []
    local = [line.strip() for line in out.splitlines() if line.strip()]
    rc, remote_out, _ = _run(
        ["git", "for-each-ref", "--format=%(refname:short)", "refs/remotes/origin/"]
    )
    if rc != 0:
        return local
    remote_set = {
        line.strip().removeprefix("origin/") for line in remote_out.splitlines() if line.strip()
    }
    return [b for b in local if b in remote_set and b != "main"]


def _open_pr_head_refs() -> set[str]:
    """Return the set of headRefName values for open PRs on the
    current repo. Empty set if gh is unavailable or returns nothing."""
    rc, out, _ = _run(
        ["gh", "pr", "list", "--state", "open", "--json", "headRefName", "--limit", "100"]
    )
    if rc != 0 or not out.strip():
        return set()
    try:
        data = json.loads(out)
    except json.JSONDecodeError:
        return set()
    return {p.get("headRefName", "") for p in data if isinstance(p, dict)}


def _guardrail_paths() -> set[str]:
    """Read scripts/guardrail_files.txt — the canonical list of files
    that require External-Review trailer on merge to main.

    Empty set if the file can't be read (fail-open: don't block PR
    opening because the file list is missing).
    """
    try:
        # Walk up from cli/prs_commands.py to repo root.
        here = Path(__file__).resolve()
        for parent in here.parents:
            candidate = parent / "scripts" / "guardrail_files.txt"
            if candidate.exists():
                lines = candidate.read_text(encoding="utf-8").splitlines()
                return {
                    line.strip()
                    for line in lines
                    if line.strip() and not line.strip().startswith("#")
                }
    except OSError:
        pass
    return set()


def _branch_touches_guardrail(branch: str, base: str = "main") -> tuple[bool, list[str]]:
    """True if any commit on ``branch`` that's not on ``base`` modifies
    a file in the guardrail list. Returns (touches, list-of-touched-files).

    Uses ``git diff --name-only base...branch`` to enumerate changed
    files since the merge-base. Fail-open on git error (returns False);
    a guardrail-detection bug should not block PR creation.
    """
    guardrails = _guardrail_paths()
    if not guardrails:
        return False, []
    rc, out, _ = _run(
        ["git", "diff", "--name-only", f"origin/{base}...{branch}"], timeout=10
    )
    if rc != 0:
        return False, []
    changed = {line.strip() for line in out.splitlines() if line.strip()}
    touched = sorted(changed & guardrails)
    return bool(touched), touched


def find_branches_without_prs() -> list[str]:
    """Pure logic split out for testability: local branches with a
    remote counterpart that don't have an open PR."""
    branches = _local_branches_with_remote()
    if not branches:
        return []
    open_heads = _open_pr_head_refs()
    return sorted(b for b in branches if b not in open_heads)


def register(cli: click.Group) -> None:
    """Register the prs command."""

    @cli.command("prs")
    @click.option(
        "--open-missing",
        is_flag=True,
        help="Run `gh pr create --fill` for each branch missing a PR.",
    )
    def prs_cmd(open_missing: bool) -> None:
        """Find local branches without an open PR; optionally open them."""
        missing = find_branches_without_prs()
        if not missing:
            click.secho("[+] All local branches with a remote have an open PR.", fg="green")
            return

        click.secho(f"\n=== {len(missing)} branch(es) need a PR ===\n", fg="cyan", bold=True)
        for b in missing:
            click.secho(f"  {b}", fg="yellow")

        if not open_missing:
            click.secho(
                "\nRe-run with --open-missing to open them via "
                "`gh pr create --fill`, or open manually.",
                fg="bright_black",
            )
            return

        click.secho("\nOpening PRs ...", fg="cyan")
        opened: list[tuple[str, str]] = []
        failed: list[tuple[str, str]] = []
        skipped_guardrail: list[tuple[str, list[str]]] = []
        for branch in missing:
            # Guardrail-aware gate (2026-06-18): if the branch touches a
            # guardrail file, refuse `--fill` because the commit message
            # almost certainly lacks the External-Review trailer (commits
            # are not blocked over missing trailers per Aletheia's
            # Finding 78). Surface the workflow instead so the operator
            # files the round + CONFIRMs + uses `divineos audit
            # prepare-merge` to generate the body.
            touches, files = _branch_touches_guardrail(branch)
            if touches:
                skipped_guardrail.append((branch, files))
                click.secho(
                    f"  [!] {branch} touches guardrail file(s); --fill would "
                    f"open a PR without the External-Review trailer. Skipping.",
                    fg="yellow",
                )
                for f in files[:3]:
                    click.secho(f"        - {f}", fg="bright_black")
                if len(files) > 3:
                    click.secho(f"        - ... and {len(files) - 3} more", fg="bright_black")
                click.secho(
                    f"      Workflow:\n"
                    f"        1. File audit round + CONFIRMs against this branch's HEAD\n"
                    f"        2. divineos audit prepare-merge <round-id> --pr-title '<title>' > body.md\n"
                    f"        3. gh pr create --base main --head {branch} --title '<title>' --body-file body.md",
                    fg="bright_black",
                )
                continue
            rc, out, err = _run(
                ["gh", "pr", "create", "--fill", "--head", branch, "--base", "main"],
                timeout=30,
            )
            if rc == 0:
                opened.append((branch, out.strip()))
                click.secho(f"  [+] {branch} -> {out.strip()}", fg="green")
            else:
                failed.append((branch, (err or out).strip()))
                click.secho(f"  [!] {branch} failed: {(err or out).strip()[:120]}", fg="red")

        click.secho(
            f"\nDone: {len(opened)} opened, {len(failed)} failed, "
            f"{len(skipped_guardrail)} skipped (guardrail-touching).",
            fg="cyan",
            bold=True,
        )
