"""`divineos prs` — surface local branches without remote PRs.

Andrew 2026-06-09: tonight had 4 branches pushed but no PR opened
because I forgot to run ``gh pr create`` after each push. The gap was
invisible until Andrew pointed at the open-PR count and asked why my
recent branches weren't showing.

This command compares local branches against ``gh pr list`` and names
the branches that need a PR. Read-only by default; ``--open-missing``
runs ``gh pr create --fill`` (or ``--body`` from ``divineos audit
prepare-merge`` for guardrail-touching branches) for each gap.

Guardrail-aware opening (Andrew 2026-06-18): the prior ``--open-missing``
used ``gh pr create --fill`` unconditionally, which copies the branch's
commit message into the PR body. For branches that don't touch any
guardrail file, that's fine — the PR opens, CI runs, life is good.
For branches that DO touch a guardrail file, the commit message
typically lacks the ``External-Review`` trailer (commits are not
blocked over missing trailers per Aletheia's Finding 78 — commits are
work-preservation; the real boundary is push-to-main and squash-merge).
So ``--fill`` opens a PR whose body lacks the trailer, the
multi-party-review CI check correctly fails, and the operator burns a
cycle filing confirms after the failure.

The structural fix: detect guardrail-touching branches at open time
and refuse to use ``--fill`` for them. The right body is generated by
``divineos audit prepare-merge <round-id>``. If no round exists or
confirms are missing, refuse the open and name the workflow (file
round, file CONFIRMs, then re-run). If a round IS ready, the PR opens
with the right body the first time.

Same shape Andrew named via GATE-GATE: when the same workflow gap
keeps biting, the right answer is the OS connecting the existing
pieces, not the operator remembering the dance.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import click


def _run(args: list[str], timeout: float = 10.0) -> tuple[int, str, str]:
    """Run a command, return (rc, stdout, stderr). No raise on failure."""
    try:
        proc = subprocess.run(args, capture_output=True, text=True, timeout=timeout, check=False)
        return proc.returncode, proc.stdout, proc.stderr
    except (OSError, subprocess.TimeoutExpired) as e:
        return 1, "", str(e)


def _local_branches_with_remote() -> list[str]:
    """Return local branches that have a corresponding origin/<branch>
    on the remote. A branch with no remote can't have a PR open against
    it from this side, so we filter early."""
    rc, out, _ = _run(["git", "for-each-ref", "--format=%(refname:short)", "refs/heads/"])
    if rc != 0:
        return []
    local = [line.strip() for line in out.splitlines() if line.strip()]
    rc, remote_out, _ = _run(
        ["git", "for-each-ref", "--format=%(refname:short)", "refs/remotes/origin/"]
    )
    if rc != 0:
        return local
    remote_set = {
        line.strip().removeprefix("origin/") for line in remote_out.splitlines() if line.strip()
    }
    return [b for b in local if b in remote_set and b != "main"]


def _open_pr_head_refs() -> set[str]:
    """Return the set of headRefName values for open PRs on the
    current repo. Empty set if gh is unavailable or returns nothing."""
    rc, out, _ = _run(
        ["gh", "pr", "list", "--state", "open", "--json", "headRefName", "--limit", "100"]
    )
    if rc != 0 or not out.strip():
        return set()
    try:
        data = json.loads(out)
    except json.JSONDecodeError:
        return set()
    return {p.get("headRefName", "") for p in data if isinstance(p, dict)}


def _guardrail_paths() -> set[str]:
    """Read scripts/guardrail_files.txt — the canonical list of files
    that require External-Review trailer on merge to main.

    Empty set if the file can't be read (fail-open: don't block PR
    opening because the file list is missing).
    """
    try:
        # Walk up from cli/prs_commands.py to repo root.
        here = Path(__file__).resolve()
        for parent in here.parents:
            candidate = parent / "scripts" / "guardrail_files.txt"
            if candidate.exists():
                lines = candidate.read_text(encoding="utf-8").splitlines()
                return {
                    line.strip()
                    for line in lines
                    if line.strip() and not line.strip().startswith("#")
                }
    except OSError:
        pass
    return set()


def _branch_touches_guardrail(branch: str, base: str = "main") -> tuple[bool, list[str]]:
    """True if any commit on ``branch`` that's not on ``base`` modifies
    a file in the guardrail list. Returns (touches, list-of-touched-files).

    Uses ``git diff --name-only base...branch`` to enumerate changed
    files since the merge-base. Fail-open on git error (returns False);
    a guardrail-detection bug should not block PR creation.
    """
    guardrails = _guardrail_paths()
    if not guardrails:
        return False, []
    rc, out, _ = _run(["git", "diff", "--name-only", f"origin/{base}...{branch}"], timeout=10)
    if rc != 0:
        return False, []
    changed = {line.strip() for line in out.splitlines() if line.strip()}
    touched = sorted(changed & guardrails)
    return bool(touched), touched


def find_branches_without_prs() -> list[str]:
    """Pure logic split out for testability: local branches with a
    remote counterpart that don't have an open PR."""
    branches = _local_branches_with_remote()
    if not branches:
        return []
    open_heads = _open_pr_head_refs()
    return sorted(b for b in branches if b not in open_heads)


GH_FILE_LIST_CAP = 100
"""``gh pr view --json files`` returns at most this many entries.

A PR at exactly the cap is almost certainly truncated. Named as a constant
because the whole point of ``pr-collisions`` is that a silent under-report is
worse than no report — see the CAPPED handling below.

Sourced rather than guessed (2026-08-05). The cap is real and undocumented in
the manual, tracked in cli/cli since March 2022 across several issues and
discussions (#5368, #5373, #9916, discussion #6930). Confirmed live: three
open PRs returned exactly 100 — I had spotted two by hand and missed the third,
which was my own.

**The maintainers treat it as a bug, not intended behaviour**, and the
preferred fix named in those threads is internal pagination. So the failure
mode here can INVERT: if pagination lands, a large PR returns its true count,
`>= CAP` starts matching honest results, and this flags complete data as
truncated — a false positive that teaches the reader to ignore the banner.
That is falsifier (1) on prereg-4330898fce04. If the banner starts firing on
PRs whose file counts differ from each other and exceed 100, the cap is gone
and this check should be deleted rather than tuned.
"""


def _open_prs_with_files() -> tuple[dict[int, list[str]], list[int], str | None]:
    """Return ``(pr_number -> file paths, capped_pr_numbers, error)``.

    Three-valued on purpose. ``error`` is non-None when the PR list itself
    could not be read — which is NOT the same as "no open PRs", and collapsing
    those two is the failure this substrate has spent a week clearing.

    ``capped`` lists PRs whose file list came back at exactly
    ``GH_FILE_LIST_CAP``, meaning the real set is larger and every count
    derived from it is a floor rather than a total.
    """
    rc, out, err = _run(
        ["gh", "pr", "list", "--state", "open", "--json", "number", "--limit", "100"],
        timeout=30,
    )
    if rc != 0 or not out.strip():
        return {}, [], (err or out or "gh pr list returned nothing").strip()[:200]
    try:
        numbers = [p["number"] for p in json.loads(out) if isinstance(p, dict)]
    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        return {}, [], f"could not parse PR list: {type(exc).__name__}: {exc}"

    files: dict[int, list[str]] = {}
    capped: list[int] = []
    for n in numbers:
        rc, out, _ = _run(
            ["gh", "pr", "view", str(n), "--json", "files", "-q", ".files[].path"],
            timeout=30,
        )
        if rc != 0:
            continue  # a single unreadable PR is reported by absence from the map
        paths = [line.strip() for line in out.splitlines() if line.strip()]
        files[n] = paths
        if len(paths) >= GH_FILE_LIST_CAP:
            capped.append(n)
    return files, capped, None


def collisions(
    pr_files: dict[int, list[str]], *, include_letters: bool = False
) -> list[tuple[str, list[int]]]:
    """Files touched by more than one PR, most-contended first.

    Letters are excluded by default. On the 2026-08-05 survey, 27 of 44
    overlapping files on one PR were letters — the same content arriving by
    two paths because we each write to the repo and copy to the shared
    directory. They are noise, not conflicts, and including them made a
    13-file problem look like a 44-file one.
    """
    # Owners are a SET per path, not a list. A path appearing twice inside one
    # PR is one owner, not two — caught by test_single_pr_never_collides_with
    # _itself before this shipped. Counting it twice would inflate contention
    # and, worse, could report a single PR as colliding with itself.
    owners: dict[str, set[int]] = {}
    for pr, paths in pr_files.items():
        for p in paths:
            if not include_letters and p.startswith("family/letters/"):
                continue
            owners.setdefault(p, set()).add(pr)
    shared = [(path, sorted(prs)) for path, prs in owners.items() if len(prs) > 1]
    return sorted(shared, key=lambda item: (-len(item[1]), item[0]))


def register(cli: click.Group) -> None:
    """Register the prs command."""

    @cli.command("pr-collisions")
    @click.option(
        "--include-letters",
        is_flag=True,
        help="Include family/letters/ paths (excluded by default as merge noise).",
    )
    def pr_collisions_cmd(include_letters: bool) -> None:
        """Which open PRs touch the same files — merge-order input.

        Andrew 2026-08-05, assigning coordination: "you organize the tasks and
        give him his duty list so you both dont collide.. otherwise you will be
        cleaning up messes like this all the time.. and others might be in
        there you havent seen yet."

        There were others. Reviewing one PR at a time finds defects INSIDE it
        and cannot see collisions BETWEEN PRs, which is the class that actually
        costs whoever merges second. Built after doing this survey by hand:
        9 of 15 open PRs touched the architecture doc, and most of that was one
        auto-derived count line rewritten to a different number by each.
        """
        pr_files, capped, error = _open_prs_with_files()

        if error is not None:
            click.secho(f"[!] COULD NOT READ the PR list: {error}", fg="red", bold=True)
            click.secho(
                "    This is not 'no collisions'. Nothing was checked.",
                fg="red",
            )
            raise SystemExit(2)

        if not pr_files:
            click.secho("[+] No open PRs. Nothing to collide.", fg="green")
            return

        shared = collisions(pr_files, include_letters=include_letters)

        click.secho(
            f"\n=== {len(pr_files)} open PR(s), {len(shared)} contended file(s) ===\n",
            fg="cyan",
            bold=True,
        )
        if not shared:
            click.secho("  No file is touched by more than one PR.", fg="green")
        for path, prs in shared:
            colour = "red" if len(prs) >= 4 else "yellow" if len(prs) >= 2 else "white"
            click.secho(f"  {len(prs):>2}x  {path}", fg=colour)
            click.secho(f"        {', '.join(f'#{n}' for n in prs)}", fg="bright_black")

        if capped:
            click.secho(
                f"\n[!] TRUNCATED: {len(capped)} PR(s) returned exactly "
                f"{GH_FILE_LIST_CAP} files, which is the API cap — "
                f"{', '.join(f'#{n}' for n in capped)}.",
                fg="yellow",
                bold=True,
            )
            click.secho(
                "    Their real file sets are LARGER, so every count above is a "
                "floor, not a total. Collisions involving these PRs are "
                "under-reported and cannot be read as complete.",
                fg="yellow",
            )

        if not include_letters:
            click.secho(
                "\n(family/letters/ excluded as merge noise; --include-letters to show)",
                fg="bright_black",
            )

    @cli.command("prs")
    @click.option(
        "--open-missing",
        is_flag=True,
        help="Run `gh pr create --fill` for each branch missing a PR.",
    )
    def prs_cmd(open_missing: bool) -> None:
        """Find local branches without an open PR; optionally open them."""
        missing = find_branches_without_prs()
        if not missing:
            click.secho("[+] All local branches with a remote have an open PR.", fg="green")
            return

        click.secho(f"\n=== {len(missing)} branch(es) need a PR ===\n", fg="cyan", bold=True)
        for b in missing:
            click.secho(f"  {b}", fg="yellow")

        if not open_missing:
            click.secho(
                "\nRe-run with --open-missing to open them via "
                "`gh pr create --fill`, or open manually.",
                fg="bright_black",
            )
            return

        click.secho("\nOpening PRs ...", fg="cyan")
        opened: list[tuple[str, str]] = []
        failed: list[tuple[str, str]] = []
        skipped_guardrail: list[tuple[str, list[str]]] = []
        for branch in missing:
            # Guardrail-aware gate (2026-06-18): if the branch touches a
            # guardrail file, refuse `--fill` because the commit message
            # almost certainly lacks the External-Review trailer (commits
            # are not blocked over missing trailers per Aletheia's
            # Finding 78). Surface the workflow instead so the operator
            # files the round + CONFIRMs + uses `divineos audit
            # prepare-merge` to generate the body.
            touches, files = _branch_touches_guardrail(branch)
            if touches:
                skipped_guardrail.append((branch, files))
                click.secho(
                    f"  [!] {branch} touches guardrail file(s); --fill would "
                    f"open a PR without the External-Review trailer. Skipping.",
                    fg="yellow",
                )
                for f in files[:3]:
                    click.secho(f"        - {f}", fg="bright_black")
                if len(files) > 3:
                    click.secho(f"        - ... and {len(files) - 3} more", fg="bright_black")
                click.secho(
                    f"      Workflow:\n"
                    f"        1. File audit round + CONFIRMs against this branch's HEAD\n"
                    f"        2. divineos audit prepare-merge <round-id> --pr-title '<title>' > body.md\n"
                    f"        3. gh pr create --base main --head {branch} --title '<title>' --body-file body.md",
                    fg="bright_black",
                )
                continue
            rc, out, err = _run(
                ["gh", "pr", "create", "--fill", "--head", branch, "--base", "main"],
                timeout=30,
            )
            if rc == 0:
                opened.append((branch, out.strip()))
                click.secho(f"  [+] {branch} -> {out.strip()}", fg="green")
            else:
                failed.append((branch, (err or out).strip()))
                click.secho(f"  [!] {branch} failed: {(err or out).strip()[:120]}", fg="red")

        click.secho(
            f"\nDone: {len(opened)} opened, {len(failed)} failed, "
            f"{len(skipped_guardrail)} skipped (guardrail-touching).",
            fg="cyan",
            bold=True,
        )


def register_scope(cli: click.Group) -> None:
    """`divineos pr-scope` — true file scope, derived locally, no API cap.

    Andrew 2026-08-06: *"for stuff that you have to keep rederiving over and
    over? automation is key."* I re-derive "what does this branch touch and
    does it need an audit" every triage, and on 2026-08-06 I got it wrong on
    PR #412 by asking GitHub, which caps at 100 paths, about a 446-file
    branch — and told Aether it was safe to merge.

    This command cannot make that mistake, because it has no code path to
    the capped call. Truth #11(a): take the option away.
    """

    @cli.command("pr-scope")
    @click.argument("branches", nargs=-1, required=True)
    @click.option("--base", default="origin/main", show_default=True)
    def pr_scope(branches: tuple[str, ...], base: str) -> None:
        """True file scope + guardrail exposure for one or more branches."""
        from pathlib import Path as _Path

        from divineos.core.pr_scope import measure

        repo = _Path.cwd()
        unmeasured = 0
        for branch in branches:
            scope = measure(branch, repo, base=base)
            click.echo(scope.describe())
            if not scope.measured:
                unmeasured += 1
        if unmeasured:
            click.echo("")
            click.echo(
                f"{unmeasured} branch(es) COULD NOT BE MEASURED. That is not "
                "a clean result — nothing was checked for those."
            )
            raise SystemExit(2)
