#!/bin/bash
# Stop doorbell. One of seven. All judgment lives in the OS.
#
# GENERATED by divineos.core.doorbell_generator. Do not hand-edit: the
# pre-commit check regenerates and compares, so an edit here is refused rather
# than kept. Change the template, not the output.
#
# Andrew 2026-06-30: "Make the hooks dumber so they can't be wrong; put the
# logic in the OS so the decision happens where the contract is."
# Andrew 2026-09-08: "all 125+ hooks could all be consolidated to 7 hooks as
# they all do the same thing, and then yes all of the logic needs to be moved
# into the OS itself."
#
# Aria 2026-09-08, on why this file is generated rather than inspected: "Do not
# police the shape. Remove the authoring. You cannot put a brain in a file you
# did not author."
#
# FAILS CLOSED, and this is the only door that does. The surfaces behind Stop
# are REFUSALS. A dead doorbell here does not produce a missing reminder; it
# produces a reply that shipped because nothing was present to refuse it, which
# is byte-identical to a reply that passed every check (Aria 2026-09-08).
#
# Only the IMPORT failure refuses. A missing repository or interpreter is the
# fresh-clone condition and still exits 0 -- refusing there would wall someone
# out of their own checkout, which is a different failure than the one this
# guards.

set +e
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
[ -z "$REPO_ROOT" ] && exit 0
# shellcheck disable=SC1091
source "$REPO_ROOT/.claude/hooks/_lib.sh" 2>/dev/null || exit 0
PYTHON_BIN="$(find_divineos_python)" || exit 0

export PYTHONIOENCODING=utf-8
HOOK_JSON="$(cat)" "$PYTHON_BIN" -c "
import json, os, sys
try:
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
except (AttributeError, OSError):
    pass
try:
    payload = json.loads(os.environ.get('HOOK_JSON', '') or '{}')
except ValueError:
    payload = {}
try:
    from divineos.core.hook_router import main
    from divineos.core.hook_surfaces import install
    install()
except Exception as exc:
    print('[doorbell Stop] NOT RUNNING: ' + type(exc).__name__ + ': ' + str(exc),
          file=sys.stderr)
    print('[doorbell Stop] every Stop surface is INERT for this call - '
          'not passing, absent.', file=sys.stderr)
    print('[doorbell Stop] REFUSING: nothing checked this reply, so it does not go out on my say-so.', file=sys.stderr)
    sys.exit(2)
sys.exit(main('Stop', payload))
"
exit $?
