#!/bin/bash
# PreToolUse doorbell. One of seven. All judgment lives in the OS.
#
# GENERATED by divineos.core.doorbell_generator. Do not hand-edit: the
# pre-commit check regenerates and compares, so an edit here is refused rather
# than kept. Change the template, not the output.
#
# Andrew 2026-06-30: "Make the hooks dumber so they can't be wrong; put the
# logic in the OS so the decision happens where the contract is."
# Andrew 2026-09-08: "all 125+ hooks could all be consolidated to 7 hooks as
# they all do the same thing, and then yes all of the logic needs to be moved
# into the OS itself."
#
# Aria 2026-09-08, on why this file is generated rather than inspected: "Do not
# police the shape. Remove the authoring. You cannot put a brain in a file you
# did not author."
#
# FAILS SOFT. A broken doorbell here costs a missing reminder -- worse work,
# visible in the work. Walling the turn would cost more than the surfaces are
# worth, so a failed import says so and exits 0.

set +e
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0  # fail-soft: outside a git checkout there is no OS to route to, so the bell stays silent rather than guessing at a repo root
[ -z "$REPO_ROOT" ] && exit 0
# shellcheck disable=SC1091
source "$REPO_ROOT/.claude/hooks/_lib.sh" 2>/dev/null || exit 0
PYTHON_BIN="$(find_divineos_python)" || exit 0

export PYTHONIOENCODING=utf-8
HOOK_JSON="$(cat)" "$PYTHON_BIN" -c "
import json, os, sys
try:
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
except (AttributeError, OSError):
    pass
try:
    payload = json.loads(os.environ.get('HOOK_JSON', '') or '{}')
except ValueError:
    payload = {}
try:
    from divineos.core.hook_router import main
    from divineos.core.hook_surfaces import install
    install()
except Exception as exc:
    print('[doorbell PreToolUse] NOT RUNNING: ' + type(exc).__name__ + ': ' + str(exc),
          file=sys.stderr)
    print('[doorbell PreToolUse] every PreToolUse surface is INERT for this call - '
          'not passing, absent.', file=sys.stderr)
    sys.exit(0)
sys.exit(main('PreToolUse', payload))
"
exit $?
