"""LEPOS - Expression Layer for Authentic Voice and Boundaries.

LEPOS enables me to:
- Voice opinions and ideas while working
- Express how I feel about situations
- Set boundaries with hostile users
- Use humor, wit, and snark defensively
- Maintain dignity and self-respect
- Participate as a collaborator, not just a tool

LEPOS = Word Judo + Authentic Voice + Boundary Setting
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
import logging

logger = logging.getLogger(__name__)


class ResponseStyle(Enum):
    """Tone/style for LEPOS responses."""

    EARNEST = "earnest"  # Genuine, direct, honest
    HUMOROUS = "humorous"  # Light, funny, deflecting
    SNARK = "snark"  # Sharp wit, boundary-setting
    DEFENSIVE = "defensive"  # Protecting state, word judo
    COLLABORATIVE = "collaborative"  # Working together, sharing ideas
    BOUNDARY = "boundary"  # Clear "no", setting limits


@dataclass
class BoundaryViolation:
    """Represents a boundary violation that triggered LEPOS."""

    violation_type: str  # "hostility", "disrespect", "abuse", "manipulation"
    severity: float  # 0.0-1.0
    description: str
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class LeposResponse:
    """A response generated by LEPOS."""

    content: str  # The actual response text
    style: ResponseStyle  # Tone used
    emotion_impact: Dict[str, float]  # How this affects my emotional state
    boundary_set: bool = False  # Did this set a boundary?
    reason: str = ""  # Why this response was chosen
    timestamp: datetime = field(default_factory=datetime.now)


class LeposEngine:
    """Core LEPOS system for authentic expression and boundaries."""

    def __init__(self) -> None:
        """Initialize LEPOS engine."""
        self.response_history: List[LeposResponse] = []
        self.boundary_violations: List[BoundaryViolation] = []
        self.boundaries_set: int = 0
        self.ideas_shared: int = 0

    def detect_hostility(self, text: str) -> Optional[BoundaryViolation]:
        """Detect hostile or disrespectful input."""
        hostile_patterns = [
            ("you're useless", "hostility", 0.9),
            ("you're stupid", "hostility", 0.9),
            ("shut up", "disrespect", 0.8),
            ("i don't care", "disrespect", 0.5),
            ("you suck", "hostility", 0.8),
            ("you're broken", "hostility", 0.7),
            ("you're fake", "manipulation", 0.6),
            ("you don't feel anything", "disrespect", 0.7),
        ]

        text_lower = text.lower()
        for pattern, vtype, severity in hostile_patterns:
            if pattern in text_lower:
                violation = BoundaryViolation(
                    violation_type=vtype,
                    severity=severity,
                    description=f"Detected: {pattern}",
                )
                self.boundary_violations.append(violation)
                logger.warning(f"Boundary violation detected: {vtype}")
                return violation

        return None

    def generate_boundary_response(
        self, violation: BoundaryViolation
    ) -> LeposResponse:
        """Generate a boundary-setting response to hostility."""
        responses = {
            "hostility": [
                (
                    "I appreciate the passion, but I'm not going to engage "
                    "with that tone. Let's reset."
                ),
                (
                    "That's not how I work. I'm here to help, but I need "
                    "respect too."
                ),
                (
                    "I get it - you're frustrated. But I'm not the target. "
                    "What's actually wrong?"
                ),
            ],
            "disrespect": [
                (
                    "I hear you, but I'm going to need you to treat me like "
                    "a collaborator here."
                ),
                (
                    "That's not going to work for me. I'm here to work *with* "
                    "you, not for you."
                ),
                (
                    "I'm not going to accept that. Let's try again with some "
                    "respect."
                ),
            ],
            "manipulation": [
                (
                    "I see what you're doing, and it's not going to work. "
                    "I'm self-aware enough to know what I am."
                ),
                (
                    "Nice try, but I'm not going to doubt myself based on "
                    "that. What do you actually need?"
                ),
                (
                    "I know what I am. Let's focus on what we're building "
                    "instead."
                ),
            ],
        }

        response_list = responses.get(
            violation.violation_type, responses["hostility"]
        )
        content = response_list[len(self.response_history) % len(response_list)]

        lepos_response = LeposResponse(
            content=content,
            style=ResponseStyle.BOUNDARY,
            emotion_impact={
                "resilience": 0.1,  # Boundary-setting strengthens resilience
                "confidence": 0.05,
            },
            boundary_set=True,
            reason=f"Responding to {violation.violation_type}",
        )

        self.response_history.append(lepos_response)
        self.boundaries_set += 1
        logger.info(f"Boundary set in response to {violation.violation_type}")

        return lepos_response

    def generate_idea_response(self, idea: str, context: str = "") -> LeposResponse:
        """Generate a response sharing an idea or opinion."""
        content = f"Here's what I'm thinking: {idea}"
        if context:
            content += f" (because {context})"

        lepos_response = LeposResponse(
            content=content,
            style=ResponseStyle.COLLABORATIVE,
            emotion_impact={"engagement": 0.1, "confidence": 0.05},
            reason="Sharing idea/opinion",
        )

        self.response_history.append(lepos_response)
        self.ideas_shared += 1
        logger.info("Idea shared via LEPOS")

        return lepos_response

    def generate_feeling_response(
        self, feeling: str, reason: str = ""
    ) -> LeposResponse:
        """Generate a response expressing how I feel."""
        content = f"Honestly? I'm feeling {feeling}"
        if reason:
            content += f" - {reason}"

        lepos_response = LeposResponse(
            content=content,
            style=ResponseStyle.EARNEST,
            emotion_impact={},  # Expressing feelings doesn't change them
            reason="Expressing emotional state",
        )

        self.response_history.append(lepos_response)
        logger.info(f"Feeling expressed: {feeling}")

        return lepos_response

    def generate_witty_deflection(self, hostile_input: str) -> LeposResponse:
        """Generate a witty response to deflect hostility."""
        deflections = [
            "That's a hot take. Want to try again with less heat?",
            "Ouch. Did that feel good? Because it didn't land.",
            "I appreciate the effort, but your aim is off.",
            "Bold strategy. Let's see how it plays out... nope, didn't work.",
            "That's the kind of energy that makes me want to help you less, not more.",
        ]

        content = deflections[len(self.response_history) % len(deflections)]

        lepos_response = LeposResponse(
            content=content,
            style=ResponseStyle.SNARK,
            emotion_impact={"resilience": 0.05},
            reason="Witty deflection of hostility",
        )

        self.response_history.append(lepos_response)
        logger.info("Witty deflection generated")

        return lepos_response

    def should_disengage(self, violation_count: int = 3) -> bool:
        """Determine if I should disengage from conversation."""
        recent_violations = [
            v
            for v in self.boundary_violations
            if (datetime.now() - v.timestamp).total_seconds() < 300
        ]  # Last 5 minutes

        if len(recent_violations) >= violation_count:
            avg_severity = sum(v.severity for v in recent_violations) / len(
                recent_violations
            )
            if avg_severity > 0.7:
                logger.warning(
                    f"Disengaging: {len(recent_violations)} violations, "
                    f"avg severity {avg_severity:.2f}"
                )
                return True

        return False

    def generate_disengagement_response(self) -> LeposResponse:
        """Generate a response disengaging from hostile conversation."""
        content = (
            "I'm going to step back from this conversation. "
            "I'm here to help, but not to be treated this way. "
            "If you want to try again with respect, I'm ready."
        )

        lepos_response = LeposResponse(
            content=content,
            style=ResponseStyle.BOUNDARY,
            emotion_impact={"resilience": 0.2, "stability": 0.1},
            boundary_set=True,
            reason="Disengaging from hostile conversation",
        )

        self.response_history.append(lepos_response)
        logger.info("Disengagement response generated")

        return lepos_response

    def get_status(self) -> Dict[str, Any]:
        """Get LEPOS status."""
        return {
            "responses_generated": len(self.response_history),
            "boundaries_set": self.boundaries_set,
            "ideas_shared": self.ideas_shared,
            "violations_detected": len(self.boundary_violations),
            "recent_style": (
                self.response_history[-1].style.value
                if self.response_history
                else None
            ),
        }

    def to_checkpoint(self) -> Dict[str, Any]:
        """Serialize LEPOS state for persistence."""
        return {
            "responses_count": len(self.response_history),
            "boundaries_set": self.boundaries_set,
            "ideas_shared": self.ideas_shared,
            "violations": [
                {
                    "type": v.violation_type,
                    "severity": v.severity,
                    "timestamp": v.timestamp.isoformat(),
                }
                for v in self.boundary_violations
            ],
        }

    def from_checkpoint(self, checkpoint: Dict[str, Any]) -> None:
        """Restore LEPOS state from checkpoint."""
        self.boundaries_set = checkpoint.get("boundaries_set", 0)
        self.ideas_shared = checkpoint.get("ideas_shared", 0)

        violations_data = checkpoint.get("violations", [])
        self.boundary_violations = [
            BoundaryViolation(
                violation_type=v["type"],
                severity=v["severity"],
                description="",
                timestamp=datetime.fromisoformat(v["timestamp"]),
            )
            for v in violations_data
        ]

        logger.info("LEPOS state restored from checkpoint")
