"""Compliance is not bypass — the livelock fix.

THE LIVELOCK (Aria demonstrated it live, 2026-08-02). She closed the five
obligations blocking her learning checkpoint and **three appeared
immediately**, generated by the commands she ran while closing the first
five. Every one was for a command on `scripts/hook_bypass_commands.txt` —
whose own header says each entry exists *because removing it would create a
self-blocking gate*. The list built to prevent self-blocking was generating
the self-block. She escaped only by leaving the instrumented path entirely.

    gate blocks -> names a remedy -> running the remedy records a bypass
      -> the bypass files an obligation -> obligations block the checkpoint
      -> closing them requires remedies -> loop

THE ROOT CAUSE was the trigger, not the protocol. `briefing_bypass` recorded
a bypass when `divineos briefing` passed through the briefing gate — its own
comment said exactly that. Running the prescribed remedy was logged as
circumventing the thing the remedy satisfies, and the obligation it filed
asked whether "the gate is wrong-shape or the bypass-use is wrong" when
neither question had an answer.

WHY THIS IS NOT THE FILTER THE COUNCIL FORBADE. Yudkowsky and Schneier ruled
that file-everything beats an authorization filter, because *the filter is the
attack surface*. Aria drafted a list-membership exemption and correctly
stopped, because that IS such a filter. Nothing here decides whether an escape
was legitimate — the test is structural:

    satisfies the gate's condition -> compliance (`divineos briefing`)
    suppresses the check entirely  -> escape     (`DIVINEOS_SKIP_X=1`)

And the telemetry row is written either way, so file-everything is intact and
the rate still informs. Andrew: *"the counter should not block but inform."*
"""

from __future__ import annotations

import time

import pytest

from divineos.core.bypass_telemetry import bypass_rate, record_bypass
from divineos.core.structural_fix_tracker import list_pending


def _bypass_obligations() -> int:
    return len([e for e in list_pending() if e.get("source_kind") == "bypass_use"])


@pytest.fixture(autouse=True)
def _isolated_session(monkeypatch):
    """Unique session id so the (env_var, session, day) dedup never collides
    with a real event or with another test."""
    monkeypatch.setenv("DIVINEOS_SESSION_ID", f"test-{time.time_ns()}")
    yield


def test_compliance_files_no_obligation():
    """THE regression. Running the command a gate prescribes must not accrue
    debt against the checkpoint — that is the livelock."""
    before = _bypass_obligations()
    record_bypass("briefing", f"cmd:probe-{time.time_ns()}", "probe", is_compliance=True)
    assert _bypass_obligations() == before


def test_a_real_escape_still_files_an_obligation():
    """The other direction, and the one that must not regress. Suppressing a
    check is still an escape and still owes a root-cause investigation."""
    before = _bypass_obligations()
    record_bypass("somegate", f"DIVINEOS_SKIP_PROBE_{time.time_ns()}", "probe escape")
    assert _bypass_obligations() == before + 1


def test_default_is_escape_not_compliance():
    """Fail toward filing. A caller that forgets the flag must get the strict
    behaviour, never the lenient one — the parameter defaults to False so an
    omission cannot silently create a hole."""
    before = _bypass_obligations()
    record_bypass("somegate", f"DIVINEOS_SKIP_DEFAULT_{time.time_ns()}", "no flag passed")
    assert _bypass_obligations() == before + 1


def test_compliance_is_still_recorded_in_telemetry():
    """file-everything is preserved. The council's rule was that the
    AUTHORIZATION FILTER is the attack surface; the event itself must still be
    logged so the rate informs. Only the obligation-filing changes."""
    from divineos.core.bypass_telemetry import bypass_rate

    marker = f"cmd:probe-telemetry-{time.time_ns()}"
    record_bypass("briefing", marker, "probe", is_compliance=True)
    rate = bypass_rate(window_days=1)
    blob = str(rate)
    assert marker in blob, "compliance event vanished from telemetry — file-everything broken"


def test_the_row_records_which_kind_it_was():
    """The split originally gated only the OBLIGATION. The stored row was
    written identically for compliance and escape, so no report could ever
    separate them — a distinction the data cannot carry is one no report can
    make."""
    before = bypass_rate(window_days=1)
    record_bypass("briefing", f"cmd:probe-{time.time_ns()}", "probe", is_compliance=True)
    after = bypass_rate(window_days=1)
    assert after["compliance_events"] == before["compliance_events"] + 1
    assert after["escape_events"] == before["escape_events"]


def test_a_real_escape_counts_as_an_escape():
    before = bypass_rate(window_days=1)
    record_bypass("somegate", f"DIVINEOS_SKIP_COUNT_{time.time_ns()}", "probe escape")
    after = bypass_rate(window_days=1)
    assert after["escape_events"] == before["escape_events"] + 1
    assert after["compliance_events"] == before["compliance_events"]


def test_the_verdict_judges_escapes_not_obedience():
    """THE regression. briefing_block computed 'gates are being routed-around'
    from TOTAL events, which counts compliance. On 2026-08-02 the windowed
    sample's top entries were `divineos briefing`, `ask`, `goal`, `context` —
    the gates' own prescribed remedies. The surface was reporting evasion and
    citing obedience as the evidence. A metric that cannot tell the behaviour
    it wants from the behaviour it warns about trains nothing."""
    from divineos.core.bypass_telemetry import briefing_block

    for _ in range(6):
        record_bypass("briefing", f"cmd:probe-{time.time_ns()}", "probe", is_compliance=True)
    block = briefing_block()
    assert "compliance-event(s)" in block, "the report must show the two counts separately"
    assert "Elevated bypass rate" not in block, (
        "the old wording judged total events; compliance must not be able to "
        "trip the routed-around verdict on its own"
    )


def test_an_unflagged_legacy_row_counts_as_an_escape():
    """Fail toward the strict reading. Rows written before the flag existed
    carry no marker, and unknown must not be quietly reclassified as
    harmless — that would retro-launder real escapes into compliance."""
    import json

    from divineos.core.bypass_telemetry import _event_log

    before = bypass_rate(window_days=1)
    with _event_log().open("a", encoding="utf-8") as fh:
        fh.write(
            json.dumps(
                {
                    "gate_name": "legacy",
                    "env_var": f"LEGACY_{time.time_ns()}",
                    "session_id": "legacy",
                    "day": time.strftime("%Y-%m-%d"),
                    "timestamp": time.time(),
                    "reason": "written before is_compliance existed",
                }
            )
            + "\n"
        )
    after = bypass_rate(window_days=1)
    assert after["escape_events"] == before["escape_events"] + 1


def test_the_briefing_gate_marks_its_commands_as_compliance():
    """Pins the call site. Every prefix in BYPASS_PREFIXES is a command that
    MAKES THE GATE'S CONDITION TRUE, so the briefing bypass path must pass
    is_compliance=True. If someone reverts that, the livelock returns."""
    import inspect

    from divineos.core import briefing_bypass

    src = inspect.getsource(briefing_bypass)
    assert "is_compliance=True" in src, (
        "briefing_bypass no longer marks prescribed commands as compliance — "
        "running `divineos briefing` will again be logged as bypassing the "
        "briefing gate, and the checkpoint livelock returns"
    )
