"""Bypass-event telemetry — track gate-bypass env-var usage over time.

Aletheia psf-ac523181 (2026-05-18): when shipping a structural change
where you're uncertain whether it'll hold, ship the change AND the
instrument that measures whether it holds. Most tonight-shipped fixes
have instruments (lepos_debt count, consultation ratio, Andrew-
correction integration-rate, survival_link). The GATES have bypass
env vars but no measurement of how often the bypass actually fires.

If bypass becomes habitual — operator (or agent) sets the env var on
every push without naming a real reason — the gate degrades to
warning. That degradation is currently invisible. This module
records each bypass invocation so the rate is queryable.

Recorded fields per event:
- gate_name (which gate was bypassed)
- env_var (which env var triggered the bypass)
- timestamp
- session_id (if available)
- reason (free-text, optional — operator can name why)
"""

from __future__ import annotations

__guardrail_required__ = True

import json
import os
import time
from pathlib import Path

from divineos.core.paths import divineos_home


def _event_log() -> Path:
    p = divineos_home() / "bypass_events.jsonl"
    p.parent.mkdir(exist_ok=True)
    return p


# env_var prefixes that identify a row's kind without needing the flag.
# These are conventions the writers already follow: a `cmd:` row records
# that a PRESCRIBED COMMAND was run to satisfy a gate; a `bypass:` row
# records a dismissal. Both were being written long before the flag existed.
_COMPLIANCE_PREFIXES = ("cmd:",)
_ESCAPE_PREFIXES = ("bypass:", "DIVINEOS_")


def _classify(rec: dict) -> str:
    """Return 'compliance', 'escape', or 'unclassified' for one row.

    Aria 2026-08-18, after Andrew caught the number. The old rule was two
    branches: flag set means compliance, ANYTHING ELSE means escape. The
    flag landed 2026-08-02, so every row older than that fell into the
    escape branch no matter what it recorded. The windowed report then
    read 48 escapes out of 52 rows and concluded "gates are being routed-
    around" — while printing, three lines below itself, the breakdown
    showing 49 of those rows were `cmd:divineos briefing` and friends.
    Those are the gate's own prescribed remedies. Running them is the
    thing the gate is asking for.

    So the metric was reporting THE AGE OF ITS OWN SCHEMA and rendering a
    verdict on my behaviour from it. Andrew estimated the true figure at
    around ten; it is three.

    The fix is not a better guess. The `env_var` field already carried the
    answer — the writers have always used `cmd:` for a satisfied gate and
    `bypass:` for a dismissal — so an unflagged row is only ambiguous if
    its prefix is also unrecognised. Those rows return 'unclassified' and
    are counted in their own bucket rather than being folded into either
    side.

    That third bucket is the whole point. "No flag" and "was an escape"
    are different facts, and the old code rendered them identically —
    the same defect the rest of this session kept finding: a check that
    cannot distinguish nothing-there from could-not-look.
    """
    if rec.get("is_compliance"):
        return "compliance"
    env = str(rec.get("env_var", "") or "")
    if env.startswith(_COMPLIANCE_PREFIXES):
        return "compliance"
    if env.startswith(_ESCAPE_PREFIXES):
        return "escape"
    return "unclassified"


def record_bypass(
    gate_name: str, env_var: str, reason: str = "", is_compliance: bool = False
) -> None:
    """Append a bypass event to the rolling log.

    Idempotent on (env_var, session_id, day) — repeated bypass within
    the same session-day collapses to one row to prevent log-spam.
    Spam would itself be a signal but the row-level signal is
    bypass-fired-today, not bypass-fired-100-times-today.

    ``is_compliance=True`` means the caller SATISFIED the gate's condition
    rather than suppressing the check — running ``divineos briefing`` to clear
    the briefing gate, for example. The event is still logged (the
    file-everything property is untouched), but no root-cause obligation is
    filed, because there is no root cause to investigate.

    WHY THIS PARAMETER EXISTS (Andrew + Aria, 2026-08-02). Aria demonstrated a
    livelock: she closed the five obligations blocking her learning checkpoint
    and three appeared immediately, generated by the commands she ran while
    closing the first five. Every one was for a command on the canonical
    bypass list — whose own header says entries exist *because removing them
    would create a self-blocking gate*.

    The trigger was wrong, not the protocol. ``briefing_bypass`` recorded a
    bypass when ``divineos briefing`` passed through the briefing gate — its
    own comment says exactly that. Running the prescribed remedy was logged as
    circumventing the thing the remedy satisfies, and the obligation it filed
    asked me to "investigate whether this gate is wrong-shape or the
    bypass-use is wrong" when neither applied.

    WHY THIS IS NOT THE FILTER THE COUNCIL FORBADE. Yudkowsky and Schneier
    ruled that file-everything beats an authorization filter, because *the
    filter is the attack surface*. Nothing here decides whether an escape was
    legitimate. The test is structural:

        satisfies the gate's condition  -> compliance  (`divineos briefing`)
        suppresses the check entirely   -> escape      (`DIVINEOS_SKIP_X=1`)

    Escapes file obligations exactly as before. And the telemetry row is
    written in both cases, so the rate still informs — which is the shape
    Andrew asked for: *"the counter should not block but inform."*
    """
    sid = os.environ.get("CLAUDE_SESSION_ID") or os.environ.get("DIVINEOS_SESSION_ID") or ""
    day = time.strftime("%Y-%m-%d")
    key = f"{env_var}:{sid}:{day}"
    log = _event_log()
    # Read existing keys for today's dedup
    existing_keys: set[str] = set()
    if log.exists():
        try:
            for line in log.read_text(encoding="utf-8").splitlines():
                if not line.strip():
                    continue
                try:
                    rec = json.loads(line)
                except (ValueError, TypeError):
                    continue
                rk = f"{rec.get('env_var', '')}:{rec.get('session_id', '')}:{rec.get('day', '')}"
                existing_keys.add(rk)
        except OSError:
            pass
    if key in existing_keys:
        return
    event = {
        "gate_name": gate_name,
        "env_var": env_var,
        "session_id": sid,
        "day": day,
        "timestamp": time.time(),
        "reason": (reason or "").strip()[:500],
        # Stored 2026-08-02. The compliance/escape split landed earlier the
        # same day but only gated the OBLIGATION -- the row was written
        # identically either way, so no report could ever separate them, and
        # briefing_block kept concluding "gates are being routed-around" from
        # a sample that was mostly the prescribed commands being run. A
        # distinction the data cannot carry is a distinction no report can
        # make.
        "is_compliance": bool(is_compliance),
    }
    try:
        with log.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(event) + "\n")
    except OSError:
        pass
    # 2026-07-22 (task #18, prereg-30485a180429, council-411666e581dd):
    # every bypass event auto-files a pending investigation obligation
    # via structural_fix_tracker. The obligation surfaces in the
    # briefing dashboard and blocks the extract pipeline (via
    # enforce_bypass_investigation_gate) until resolved. Andrew
    # directive 93164891: "A bypass or escape hatch is last resort so
    # any use of them gets logged and needs to automatically launch a
    # root cause investigation." Truth #10: feed the optimizer cost
    # data in its own currency — every bypass costs a real followup
    # task. Council walk file-ALL decision per Yudkowsky + Schneier:
    # authorization-filter is the attack surface; better to file all
    # and require corroborator on resolution. Corroborator-resolution
    # enforcement is task #24 followup. This filing wire is
    # best-effort: if structural_fix_tracker is unavailable, the
    # telemetry event still lands and the bypass is not lost.
    # Compliance files no obligation. The obligation's own text asks whether
    # the gate is wrong-shape or the bypass-use is wrong; when the command
    # SATISFIED the gate, neither question has an answer, and an unanswerable
    # investigation is the painted-door shape — a remedy that cannot be
    # completed. The telemetry row above is already written, so the event is
    # still counted and still informs.
    if is_compliance:
        return

    try:
        from divineos.core.structural_fix_tracker import record_pending_fix

        record_pending_fix(
            content=(
                f"Root-cause investigation owed: bypass of gate "
                f"'{gate_name}' via env var '{env_var}' on "
                f"{time.strftime('%Y-%m-%d')}. Reason given: "
                f"{(reason or '(none)').strip()[:200]}. Investigate "
                f"whether this gate is wrong-shape (frequent legitimate "
                f"bypass = gate discipline is off) or the bypass-use "
                f"is wrong (frequent bypass without operator "
                f"authorization = my discipline is off). Resolve by "
                f"either landing a structural fix to the gate OR "
                f"citing an operator-authorization corroborator."
            ),
            trigger=f"bypass:{env_var}",
            source_kind="bypass_use",
        )
    except Exception:  # noqa: BLE001 - fail-open on tracker import
        pass


def bypass_rate(window_days: int = 14) -> dict:
    """Return bypass-rate stats over the window.

    Returns:
        total_events: int — number of distinct (env_var, session, day) bypass-events
        by_env_var: dict[str, int] — count per env_var
        unique_days: int — number of distinct days with at least one bypass
    """
    log = _event_log()
    if not log.exists():
        return {
            "total_events": 0,
            "compliance_events": 0,
            "escape_events": 0,
            # Present on BOTH exits. Added to the populated return first and
            # missed here, so a caller on the empty-log path got a KeyError —
            # a function with two exits and one of them updated, which is the
            # same shape as everything else found tonight, in the fix for it.
            "unclassified_events": 0,
            "by_env_var": {},
            "unique_days": 0,
            "window_days": window_days,
        }
    cutoff = time.time() - (window_days * 86400.0)
    by_env: dict[str, int] = {}
    days: set[str] = set()
    total = 0
    compliance = 0
    escapes = 0
    unclassified = 0
    try:
        for line in log.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            try:
                rec = json.loads(line)
            except (ValueError, TypeError):
                continue
            if rec.get("timestamp", 0) < cutoff:
                continue
            total += 1
            kind = _classify(rec)
            if kind == "compliance":
                compliance += 1
            elif kind == "escape":
                escapes += 1
            else:
                unclassified += 1
            by_env[rec.get("env_var", "?")] = by_env.get(rec.get("env_var", "?"), 0) + 1
            days.add(rec.get("day", ""))
    except OSError:
        pass
    return {
        "total_events": total,
        "compliance_events": compliance,
        "escape_events": escapes,
        "unclassified_events": unclassified,
        "by_env_var": by_env,
        "unique_days": len(days),
        "window_days": window_days,
    }


def full_history_stats() -> dict:
    """Return full-history bypass stats — since first-recorded event.

    Fixes the subset-is-not-the-whole violation (Andrew 2026-05-20,
    council-8faadb872d0b): the windowed ``bypass_rate()`` presents a
    14-day sample and misreads as-if-total when the surface names only
    the window. This function reports the invariant that lets the
    observer compare the sample to the whole.

    Returns:
        total_events_all_time: int — every distinct (env, session, day)
            row on record, no window filter
        first_recorded_date: str — YYYY-MM-DD of earliest event, or ""
            if log is empty
        unique_days_all_time: int — distinct days with any bypass
            across the whole history
        days_since_first: float — wall-clock days from first-event to
            now (0.0 if log is empty)
        events_per_day_avg: float — total_events_all_time / max(1.0,
            days_since_first), or 0.0 if empty

    Boundary behavior (Knuth walk council-8faadb872d0b): empty log
    returns all zeros with first_recorded_date="". Corrupted lines
    skipped (fail-open on record-level, same as bypass_rate). Missing
    timestamp fields skipped from the earliest-event calculation.
    Future timestamps (clock-drift or manual edits) are clamped so
    days_since_first is never negative.
    """
    log = _event_log()
    empty_result = {
        "total_events_all_time": 0,
        "first_recorded_date": "",
        "unique_days_all_time": 0,
        "days_since_first": 0.0,
        "events_per_day_avg": 0.0,
    }
    if not log.exists():
        return empty_result
    total = 0
    escapes = 0
    days: set[str] = set()
    earliest_ts: float | None = None
    try:
        for line in log.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            try:
                rec = json.loads(line)
            except (ValueError, TypeError):
                continue
            total += 1
            if _classify(rec) == "escape":
                escapes += 1
            days.add(rec.get("day", ""))
            ts = rec.get("timestamp")
            if isinstance(ts, (int, float)) and ts > 0:
                if earliest_ts is None or ts < earliest_ts:
                    earliest_ts = ts
    except OSError:
        return empty_result
    if total == 0 or earliest_ts is None:
        return empty_result
    now = time.time()
    days_since_first = max(0.0, (now - earliest_ts) / 86400.0)
    events_per_day_avg = total / max(1.0, days_since_first)
    # Escapes get their own rate. The verdict downstream judges on THIS,
    # not on events_per_day_avg — which counts obedience. Fixing only the
    # windowed half left the full-history half still concluding
    # "routed-around" from 203 rows that are overwhelmingly prescribed
    # commands. Same defect, second location; found by watching the
    # briefing print the corrected windowed line and the uncorrected
    # full-history verdict in the same block. (Aria 2026-08-18)
    escape_per_day_avg = escapes / max(1.0, days_since_first)
    first_date = time.strftime("%Y-%m-%d", time.gmtime(earliest_ts))
    return {
        "total_events_all_time": total,
        "escape_events_all_time": escapes,
        "first_recorded_date": first_date,
        "unique_days_all_time": len(days),
        "days_since_first": round(days_since_first, 1),
        "events_per_day_avg": round(events_per_day_avg, 2),
        "escapes_per_day_avg": round(escape_per_day_avg, 2),
    }


def briefing_block() -> str:
    """Briefing surface — empty unless bypasses fired recently.

    Post-fix (council-8faadb872d0b, 2026-07-21): surface shows BOTH
    the windowed sample AND the full-history counts so the observer
    can compare — closing the subset-is-not-the-whole violation.
    Every number is labeled with its scope (Norman gulf-of-evaluation)
    so the reader cannot conflate windowed with full-history.
    """
    stats = bypass_rate()
    full = full_history_stats()
    if stats["total_events"] == 0 and full["total_events_all_time"] == 0:
        return ""
    lines = [
        "## GATE BYPASS TELEMETRY",
        "",
        "### Windowed (recent sample)",
        f"{stats.get('escape_events', stats['total_events'])} escape(s), "
        f"{stats.get('compliance_events', 0)} compliance-event(s)"
        + (
            f", {stats['unclassified_events']} unclassified"
            if stats.get("unclassified_events")
            else ""
        )
        + f" across {stats['unique_days']} distinct day(s), "
        f"within the last {stats['window_days']} days.",
        "  (compliance = ran the command the gate prescribes, which satisfies "
        "it rather than evading it. Rows without the flag are classified by "
        "env_var prefix — cmd: is a prescribed command, bypass:/DIVINEOS_ is a "
        "dismissal — and anything unrecognised is counted as unclassified "
        "rather than assumed. Unknown is its own answer, not a quiet escape.)",
    ]
    if stats["by_env_var"]:
        lines.append("By gate-bypass env var (windowed):")
        for env, count in sorted(stats["by_env_var"].items(), key=lambda x: -x[1]):
            lines.append(f"  - {env}: {count}")
    if full["total_events_all_time"]:
        lines.append("")
        lines.append("### Full history (since first recorded event)")
        lines.append(
            f"{full['total_events_all_time']} total event(s) since "
            f"{full['first_recorded_date']} "
            f"({full['days_since_first']} days elapsed, "
            f"{full['unique_days_all_time']} distinct active day(s), "
            f"avg {full['events_per_day_avg']} events/day)."
        )
    # Elevated-rate call-to-action recomputed against BOTH scales
    # (Norman walk). Windowed threshold: 5-in-14-days ≈ 0.36/day.
    # Full-history threshold: sustained avg >= 0.5 events/day OR
    # more than 20 total events (indicates habituation across time).
    # JUDGE ON ESCAPES, NOT ON OBEDIENCE (2026-08-02). This was computed from
    # total_events, which counts compliance -- running the very command the
    # gate prescribes. On the day this changed, the windowed sample's top
    # entries were `divineos briefing`, `ask`, `goal`, `context`, `recall`:
    # the documented remedies. The surface was reporting that gates were
    # being routed around, using as its evidence the fact that they were
    # being obeyed. A metric that reads compliance as evasion cannot tell the
    # behaviour it wants from the behaviour it warns about, so it trains
    # nothing -- and it says so to Andrew in the briefing.
    # UNCLASSIFIED IS ITS OWN ALARM, and deliberately not the same one.
    #
    # test_an_unflagged_legacy_row_counts_as_an_escape pinned the old
    # arithmetic with a real concern underneath it: "unknown must not be
    # quietly reclassified as harmless." Correct. But the old code answered
    # that by calling unknown an ESCAPE, which is a claim about MY behaviour
    # made from a row nobody can read. That is how 49 obediences became a
    # verdict that I route around gates.
    #
    # So unknown gets an alarm of its own, worded as what it is: a defect in
    # the instrument, not a finding about the operator. Conflating "I cannot
    # classify this" with "you evaded" is the exact merge this whole fix
    # exists to undo. (Aria 2026-08-18)
    unclassified = stats.get("unclassified_events", 0)
    if unclassified >= 3:
        lines.append("")
        lines.append(
            f"UNCLASSIFIED ROWS: {unclassified} windowed row(s) carry no "
            "compliance flag and no recognised env_var prefix, so this metric "
            "cannot say whether they were escapes or prescribed commands. "
            "That is a gap in the instrument, NOT a finding about behaviour — "
            "it is reported rather than assumed in either direction. Fix by "
            "giving the writing call site a cmd:/bypass: prefix or the flag."
        )

    windowed_elevated = stats.get("escape_events", stats["total_events"]) >= 5
    # Judged on ESCAPES here too. The 2026-08-02 fix corrected the windowed
    # branch and left this one reading total_events_all_time, so the surface
    # kept announcing "routed-around" from a full history that is mostly
    # obedience. Fixing half a metric leaves a metric that is still wrong and
    # now harder to doubt, because the corrected half looks careful.
    full_history_elevated = (
        full.get("escapes_per_day_avg", full["events_per_day_avg"]) >= 0.5
        or full.get("escape_events_all_time", full["total_events_all_time"]) >= 20
    )
    if windowed_elevated or full_history_elevated:
        lines.append("")
        which = []
        if windowed_elevated:
            which.append("windowed sample")
        if full_history_elevated:
            which.append("full-history rate")
        lines.append(
            f"Elevated ESCAPE rate ({' + '.join(which)}) -- gates are being "
            "routed-around. Compliance is excluded from this verdict: running "
            "a gate's prescribed command satisfies it and is not evasion. "
            "Per psf-ac523181: bypass habituation degrades the "
            "gate to warning. Investigate whether the gates are wrong-shape "
            "or the bypass-discipline is."
        )
    return "\n".join(lines)


__all__ = ["record_bypass", "bypass_rate", "full_history_stats", "briefing_block"]
