"""Memory Consolidation — Knowledge Store (backward-compatibility shim).

All logic has been moved to divineos.core.knowledge sub-modules.
This file re-exports every public name so existing imports continue to work.
"""

# ruff: noqa: F401 — re-exports for backward compatibility
from divineos.core.knowledge import (
    KNOWLEDGE_MATURITY,
    KNOWLEDGE_SOURCES,
    KNOWLEDGE_TYPES,
    _ALTERNATIVE_PATTERNS,
    _CHECK_TO_CATEGORY,
    _CONVERSATIONAL_NOISE,
    _KNOWLEDGE_COLS,
    _KNOWLEDGE_COLS_K,
    _LESSON_CATEGORIES,
    _MIGRATION_RULES,
    _MIN_CONTENT_WORDS,
    _REASON_PATTERNS,
    _STOPWORDS,
    _SYSTEM_ARTIFACT,
    _TEMPORAL_CONTENT_MARKERS,
    _VACUOUS_PHRASES,
    _adjust_confidence,
    _build_fts_query,
    _categorize_correction,
    _compute_overlap,
    _decide_operation,
    _distill_correction,
    _distill_preference,
    _extract_assistant_summary,
    _extract_key_terms,
    _extract_user_text_from_record,
    _find_alternative_in_text,
    _find_reason_in_text,
    _get_connection,
    _has_temporal_markers,
    _is_extraction_noise,
    _is_noise_correction,
    _is_vacuous_summary,
    _lesson_row_to_dict,
    _normalize_text,
    _resolve_lesson,
    _row_to_dict,
    _search_knowledge_legacy,
    apply_session_feedback,
    check_recurring_lessons,
    clear_lessons,
    compute_effectiveness,
    compute_hash,
    consolidate_related,
    deep_extract_knowledge,
    extract_lessons_from_report,
    extract_session_topics,
    find_similar,
    generate_briefing,
    get_knowledge,
    get_lesson_summary,
    get_lessons,
    get_unconsolidated_events,
    health_check,
    init_knowledge_table,
    knowledge_health_report,
    knowledge_stats,
    mark_lesson_improving,
    migrate_knowledge_types,
    rebuild_fts_index,
    record_access,
    record_lesson,
    search_knowledge,
    store_knowledge,
    store_knowledge_smart,
    supersede_knowledge,
    update_knowledge,
)
