"""The seven bells are generated, so nobody can put a brain in one.

Aria, 2026-09-08, refusing the check I was about to build:

    *"Do not police the shape. Remove the authoring. ... If the bells are
    generated from that table, there is nothing to check, because nobody writes
    a bell. You cannot put a brain in a file you did not author."*

I had started on a property check — a hook may be a bell but never a brain, no
branching outside the fail-soft preamble. She killed it with the argument the
keyword-enforcement doorman makes about every detector of its class: shell's
ways of branching are not a closed set. Two chained commands, a default inside
a parameter expansion, a condition computed in a subshell and passed as an
argument, a flag decided shell-side. Each one moves the decision without typing
a word any list would hold.

So this is truth #11's FIRST remediation — take the option away — rather than
the third, which is where both of us had been reaching all day. The fail-soft
preamble exists once and is correct everywhere by construction. A hand-written
hook becomes the exception that has to say why, which is a far smaller thing to
guard than the shape of a hundred files.

## Two failure directions, chosen by what silence costs

Also hers, and the sharper half:

    *"At compose-start a dead doorbell means a missing reminder ... At Stop,
    the things behind the door are the refusals. A dead doorbell there produces
    a reply that shipped because nothing was present to refuse it, and that
    looks identical to a reply that passed every check."*

So ``Stop`` **fails closed** and every other door fails soft. Same template,
one flag, and the flag is set by what a silent failure costs rather than by a
house style.

The loop guard is what makes fail-closed survivable: a broken import must not
wedge the session forever, so the refusal is the IMPORT case only. A missing
repository or interpreter — the fresh-clone condition — still exits 0 on every
door, because refusing there would wall someone out of their own checkout.

## Why a template rather than a shared base

There are seven of these and they are shell, not Python. The generator holds
the one true body; the events are data. Regenerate-and-compare is then an
exhaustive check — byte equality against what the generator produces — rather
than a heuristic about what a bell looks like.
"""

from __future__ import annotations

from pathlib import Path

from divineos.core.hook_router import EVENTS

HOOKS_DIR = ".claude/hooks"

#: Doors whose surfaces REFUSE rather than report. A dead doorbell here would
#: let a reply ship because nothing was present to stop it, so it fails closed.
FAIL_CLOSED: frozenset[str] = frozenset({"Stop"})

_HEADER = """#!/bin/bash
# {event} doorbell. One of seven. All judgment lives in the OS.
#
# GENERATED by divineos.core.doorbell_generator. Do not hand-edit: the
# pre-commit check regenerates and compares, so an edit here is refused rather
# than kept. Change the template, not the output.
#
# Andrew 2026-06-30: "Make the hooks dumber so they can't be wrong; put the
# logic in the OS so the decision happens where the contract is."
# Andrew 2026-09-08: "all 125+ hooks could all be consolidated to 7 hooks as
# they all do the same thing, and then yes all of the logic needs to be moved
# into the OS itself."
#
# Aria 2026-09-08, on why this file is generated rather than inspected: "Do not
# police the shape. Remove the authoring. You cannot put a brain in a file you
# did not author."
"""

_FAIL_SOFT_NOTE = """#
# FAILS SOFT. A broken doorbell here costs a missing reminder -- worse work,
# visible in the work. Walling the turn would cost more than the surfaces are
# worth, so a failed import says so and exits 0.
"""

_FAIL_CLOSED_NOTE = """#
# FAILS CLOSED, and this is the only door that does. The surfaces behind Stop
# are REFUSALS. A dead doorbell here does not produce a missing reminder; it
# produces a reply that shipped because nothing was present to refuse it, which
# is byte-identical to a reply that passed every check (Aria 2026-09-08).
#
# Only the IMPORT failure refuses. A missing repository or interpreter is the
# fresh-clone condition and still exits 0 -- refusing there would wall someone
# out of their own checkout, which is a different failure than the one this
# guards.
"""

_BODY = """
set +e
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0  # fail-soft: outside a git checkout there is no OS to route to, so the bell stays silent rather than guessing at a repo root
[ -z "$REPO_ROOT" ] && exit 0
# shellcheck disable=SC1091
source "$REPO_ROOT/.claude/hooks/_lib.sh" 2>/dev/null || exit 0
PYTHON_BIN="$(find_divineos_python)" || exit 0

export PYTHONIOENCODING=utf-8
HOOK_JSON="$(cat)" "$PYTHON_BIN" -c "
import json, os, sys
try:
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
except (AttributeError, OSError):
    pass
try:
    payload = json.loads(os.environ.get('HOOK_JSON', '') or '{{}}')
except ValueError:
    payload = {{}}
try:
    from divineos.core.hook_router import main
    from divineos.core.hook_surfaces import install
    install()
except Exception as exc:
    print('[doorbell {event}] NOT RUNNING: ' + type(exc).__name__ + ': ' + str(exc),
          file=sys.stderr)
    print('[doorbell {event}] every {event} surface is INERT for this call - '
          'not passing, absent.', file=sys.stderr)
{absent_extra}    sys.exit({absent_exit})
sys.exit(main('{event}', payload))
"
exit $?
"""

_ABSENT_EXTRA_CLOSED = (
    "    print('[doorbell {event}] REFUSING: nothing checked this reply, so it "
    "does not go out on my say-so.', file=sys.stderr)\n"
)


def render(event: str) -> str:
    """The full text of one doorbell."""
    if event not in EVENTS:
        raise ValueError(f"unknown hook event {event!r}; known: {', '.join(EVENTS)}")
    closed = event in FAIL_CLOSED
    text = _HEADER.format(event=event)
    text += _FAIL_CLOSED_NOTE if closed else _FAIL_SOFT_NOTE
    text += _BODY.format(
        event=event,
        absent_exit=2 if closed else 0,
        absent_extra=(_ABSENT_EXTRA_CLOSED.format(event=event) if closed else ""),
    )
    return text


def path_for(event: str, root: Path | str = ".") -> Path:
    """Where the doorbell for ``event`` lives."""
    slug = "".join("-" + c.lower() if c.isupper() else c for c in event).lstrip("-")
    return Path(root) / HOOKS_DIR / f"doorbell-{slug}.sh"


def _read_exact(path: Path) -> str:
    """File contents with line endings untranslated.

    ``read_text`` and ``write_text`` both translate on Windows, which meant the
    first generated batch landed with carriage returns and shellcheck refused
    every one of them -- while a naive comparison would have called them
    identical, because the read translated them straight back. Byte-exact both
    ways, or the drift check is checking its own translation.
    """
    with path.open(encoding="utf-8", newline="") as handle:
        return handle.read()


def _write_exact(path: Path, text: str) -> None:
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def active_events() -> tuple[str, ...]:
    """Doors that actually have surfaces behind them.

    A bell for a door with nobody behind it is a file connected to nothing --
    the dark-hook shape the wiring checker exists to catch, and one I spent
    this same session clearing out of this directory. So the generated set
    grows as surfaces move rather than standing at seven from the start.

    Fails loud rather than assuming: if the roster cannot be loaded, that is
    not the same as no surfaces existing.
    """
    from divineos.core.hook_router import registered
    from divineos.core.hook_surfaces import install

    install()
    return tuple(e for e in EVENTS if registered(e))


def write_all(root: Path | str = ".") -> list[Path]:
    """Write a doorbell for every door that has surfaces. Returns what changed."""
    changed: list[Path] = []
    for event in active_events():
        path = path_for(event, root)
        text = render(event)
        old = _read_exact(path) if path.exists() else None
        if old != text:
            _write_exact(path, text)
            changed.append(path)
    return changed


def drifted(root: Path | str = ".") -> dict[str, str]:
    """Doorbells whose file no longer matches the generator, mapped to why.

    This is the whole check, and it is exhaustive rather than heuristic: there
    is no judgement here about what a bell should look like, only whether the
    file on disk is what the generator produces.
    """
    out: dict[str, str] = {}
    active = active_events()
    for event in active:
        path = path_for(event, root)
        if not path.exists():
            out[event] = "missing"
        elif _read_exact(path) != render(event):
            out[event] = "hand-edited"
    # A bell left standing after its last surface moved away is the same
    # dark-file shape from the other direction, so it is reported too.
    for event in EVENTS:
        if event not in active and path_for(event, root).exists():
            out[event] = "no surfaces behind it — delete the bell or wire a surface"
    return out


def main(root: Path | str = ".") -> int:
    """Pre-commit entry point. 1 blocks the commit."""
    import sys

    try:
        problems = drifted(root)
    except (OSError, ValueError) as exc:
        print(f"[doorbells] COULD NOT CHECK: {type(exc).__name__}: {exc}", file=sys.stderr)
        print("[doorbells] this is not the same as the check passing.", file=sys.stderr)
        # The EXIT CODE is deliberately the same as a clean tree: a checker
        # that wedges every commit when it breaks is deleted within a day and
        # then guards nothing. What differs is what gets SAID, and the two
        # lines above say it in the words this substrate has settled on.
        #
        # I nearly added a must-read arming here and the pre-reg gate refused
        # it, correctly. That mechanism already exists on the router; a second
        # copy would be the reflex this whole change is about. It also would
        # not fire where it matters -- this runs inside git's own process, not
        # a tool call, so there is no next tool call for it to stop.
        return 0  # both-empty: same action by design (a checker must never block a commit); the meaning is carried by the two printed lines
    if not problems:
        return 0  # both-empty: a clean tree and an unrunnable check agree only on the exit code, deliberately
    print("[doorbells] BLOCKED — a generated bell was hand-edited or is missing:", file=sys.stderr)
    for event, why in sorted(problems.items()):
        print(f"    {event}: {why}  ({path_for(event, root)})", file=sys.stderr)
    print(
        "\n  These are generated so nobody can put a decision in one.\n"
        "  Change divineos.core.doorbell_generator, then:\n"
        "      divineos hook-layer doorbells --write",
        file=sys.stderr,
    )
    return 1
