"""Replace a module's functions with hollow stubs, then run its tests.

Andrew, 2026-08-17:

    *"do not rely on tests, they are dumb lol i could write a consciousness
    module that generates magic numbers relating to your consciousness that
    mean nothing and do nothing.. and all tests would pass.. as it generated
    the number"*

    *"always try to break your stuff when building it, the happy path is a
    narrow path, that is why nothing feels wrong.. same analogy as the system
    that never fails.. maybe it hasnt.. but has it been truly tested?"*

A passing suite is not evidence that the code is right. It is evidence that
the code and the tests agree, and they usually agree because the same
understanding produced both. The third source for a test is SABOTAGE: break
the thing on purpose and see whether the test notices. A test that survives
total hollowing was never testing anything.

## What this does

Monkeypatches every public function in the target module to return a hollow
value of its annotated return type — `[]`, `{}`, `""`, `0`, `0.0`, `False`,
`None` — then runs the named test file. Every test that still passes is
reported, because each one is a test the module could be deleted under.

## What it does NOT do

It does not prove a surviving test is worthless. Some tests legitimately assert
that a function is CALLABLE, or that an empty state renders without crashing;
those should survive and are worth having. The output is a list to READ, not a
verdict to act on — the same discipline the correction-shape detector needed
(Andrew: *"this matches the correction shape.. look at it"*).

What it does prove is the converse, and that is the useful direction: a test
that survives is not evidence the computation is correct, so it must not be
counted as such.

## Why not mutation testing

`scripts/run_mutmut.py` exists and is better — it makes small semantic edits
and is far more thorough. It is also slow enough that it does not get run while
building, which is exactly when Andrew says the breaking should happen. This is
the cheap version that fits in the build loop. Use both; this one first.

Usage:
    python scripts/hollow_out.py divineos.core.self_model tests/test_self_model.py
"""

from __future__ import annotations

import argparse
import importlib
import inspect
import subprocess
import sys
import tempfile
import typing
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Hollow value per annotated return type. Deliberately the EMPTY member of each
# type: a stub returning [] or 0.0 is the magic-number module in its purest
# form -- right shape, no content.
_HOLLOW: dict[object, object] = {
    list: [],
    dict: {},
    str: "",
    int: 0,
    float: 0.0,
    bool: False,
    tuple: (),
    set: (),
    type(None): None,
}


def _hollow_for(fn) -> object:
    """Empty value matching the function's annotated return, or None."""
    try:
        hints = typing.get_type_hints(fn)
    except Exception:  # noqa: BLE001 — an unresolvable annotation is not fatal
        return None
    ret = hints.get("return")
    if ret is None:
        return None
    origin = typing.get_origin(ret) or ret
    for kind, value in _HOLLOW.items():
        if origin is kind:
            # copy so a test mutating the stub cannot poison later calls
            return list(value) if kind is list else dict(value) if kind is dict else value
    return None


def build_conftest(module_name: str) -> str:
    mod = importlib.import_module(module_name)
    lines = [
        '"""Generated by scripts/hollow_out.py. Do not commit."""',
        "import pytest",
        f"import {module_name} as _M",
        "",
        "@pytest.fixture(autouse=True)",
        "def _hollow(monkeypatch):",
    ]
    patched = 0
    for name, fn in vars(mod).items():
        if not inspect.isfunction(fn) or fn.__module__ != module_name:
            continue
        if name.startswith("__"):
            continue
        value = repr(_hollow_for(fn))
        lines.append(f"    monkeypatch.setattr(_M, {name!r}, lambda *a, **k: {value})")
        patched += 1
    if not patched:
        lines.append("    pass")
    return "\n".join(lines) + "\n", patched


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("module", help="e.g. divineos.core.self_model")
    ap.add_argument("tests", help="e.g. tests/test_self_model.py")
    args = ap.parse_args()

    conftest, patched = build_conftest(args.module)
    if not patched:
        print(f"[hollow-out] {args.module} has no module-level functions to hollow.")
        return 0

    src = REPO / args.tests
    if not src.is_file():
        print(f"[hollow-out] no such test file: {src}", file=sys.stderr)
        return 2

    with tempfile.TemporaryDirectory(prefix="hollow-") as tmp:
        d = Path(tmp)
        (d / "conftest.py").write_text(conftest, encoding="utf-8")
        (d / src.name).write_text(
            src.read_text(encoding="utf-8", errors="replace"), encoding="utf-8"
        )
        proc = subprocess.run(
            [
                sys.executable,
                "-m",
                "pytest",
                str(d / src.name),
                "-q",
                "--tb=no",
                "-p",
                "no:cacheprovider",
            ],
            cwd=REPO,
            capture_output=True,
            # PIN THE ENCODING. text=True decodes with the locale codec; on
            # Windows that is cp1252, and one em dash in a test docstring kills
            # the reader thread and empties stdout with exit 0 -- which here
            # would read as "no tests survived", the most flattering possible
            # wrong answer. Third instance of this exact failure found today.
            encoding="utf-8",
            errors="replace",
        )
    out = proc.stdout or ""
    tail = [ln for ln in out.splitlines() if ln.strip()][-1:] or ["<no output>"]

    print(f"[hollow-out] {args.module}: {patched} function(s) replaced with empty values")
    print(f"[hollow-out] running {args.tests} against the hollowed module")
    print(f"             {tail[0]}")
    print()
    if " passed" in out and " failed" not in out:
        print("  EVERY TEST SURVIVED TOTAL HOLLOWING.")
        print("  The module can be deleted and this suite still goes green, so")
        print("  the suite is not evidence that the computation is correct.")
        print("  Read the tests and ask what each one would have to see to fail.")
    elif " failed" in out:
        print("  Some tests failed under hollowing — those are the ones doing work.")
        print("  The survivors are still worth reading; some legitimately assert")
        print("  that an empty state renders, which is a real thing to want.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
