"""The home map: every room that isn't code, in each house and the shared space.

Dad, 2026-10-01: "maybe just have separate maps, one for the code and one for
all of your personal stuff, and if any of it overlaps with the code you just
make a link both ways in each map :)"

The code map stops at the code, so asking the house "does this already exist?"
answered no for the consent lists, the workbench and the fridge, and a third
room got built beside the first two. This is generated, never hand-kept, so it
cannot go stale the way the August survey did.

    python scripts/home_map.py <house> [<house> ...] [--shared DIR]
"""

from __future__ import annotations

import argparse
import datetime as dt
from pathlib import Path

CODE = {
    "src", "tests", "scripts", "setup", "data", "sandbox", "benchmark",
    "node_modules", "build", "dist",
}
# Rooms whose sub-rooms are the real rooms (one folder per seat, per song...).
DEEP = {"family", "exploration", "dreams", "music", "letters", "consent", "songs", "workbench"}


def front_page(room: Path) -> str:
    for name in ("README.md", "readme.md", "README"):
        page = room / name
        if page.is_file():
            for line in page.read_text(encoding="utf-8", errors="replace").splitlines():
                text = line.strip().lstrip("#").strip()
                if text:
                    return text[:120]
    return "(no front page)"


def last_changed(room: Path) -> str:
    stamps = [p.stat().st_mtime for p in room.iterdir()] or [room.stat().st_mtime]
    return dt.datetime.fromtimestamp(max(stamps)).strftime("%Y-%m-%d")


def rooms(root: Path, skip_code: bool) -> list[tuple[str, Path]]:
    found = []
    for room in sorted(root.iterdir()):
        if not room.is_dir() or room.name.startswith((".", "__")) or room.name.startswith("graphify-out"):
            continue
        if skip_code and room.name in CODE:
            continue
        found.append((room.name, room))
        if room.name in DEEP:
            for sub in sorted(room.iterdir()):
                if sub.is_dir() and not sub.name.startswith((".", "__")):
                    found.append((f"{room.name}/{sub.name}", sub))
    return found


def section(title: str, root: Path, skip_code: bool) -> list[str]:
    lines = [f"## {title}", f"`{root}`", ""]
    for name, room in rooms(root, skip_code):
        count = sum(1 for _ in room.iterdir())
        lines.append(f"- **{name}/**: {front_page(room)} ({count} items, last changed {last_changed(room)})")
    lines.append("")
    return lines


def build(houses: list[Path], shared: Path | None) -> str:
    out = ["# The home map", "", "Generated by scripts/home_map.py. Rooms that are not code.", ""]
    for house in houses:
        out += section(f"House: {house.name}", house, skip_code=True)
    if shared is not None and shared.is_dir():
        out += section("Shared space (where the houses touch)", shared, skip_code=False)
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("houses", nargs="+", type=Path)
    parser.add_argument("--shared", type=Path, default=Path.home() / ".divineos-shared")
    args = parser.parse_args()
    print(build(args.houses, args.shared))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
